import{useEffect,useState}from'react';import{api}from'../api';import{CalendarDays,Dumbbell,FileText,GraduationCap,Plus,Trash2,WalletCards}from'lucide-react';import{Empty,Modal,Notice,Title,money}from'../components/UI';
const load=(p:string,s:(x:any)=>void):void=>{void api(p).then(s)};
export function Reports(){const[d,setD]=useState<any>();useEffect(()=>{load('/reports',setD)},[]);return <><Title title="Relatórios" sub="Indicadores de operação e produtividade"/><div className="report-grid">{[['Ordens por status',d?.by_status],['Serviços mais solicitados',d?.by_service],['Produtividade por funcionário',d?.by_employee]].map(([title,rows]:any)=><article className="panel report"><h3>{title}</h3>{rows?.map((x:any)=><div><span>{x.label}</span><b>{x.value}</b><i style={{width:`${Math.min(100,x.value*8)}%`}}/></div>)}</article>)}</div></>}
export function Notifications(){const[rows,setRows]=useState<any[]>([]);const reload=()=>load('/notifications',setRows);useEffect(reload,[]);return <><Title title="Notificações" sub="Atualizações importantes da operação"/><div className="panel feed">{rows.map(x=><button className={x.read?'read':''} onClick={async()=>{await api(`/notifications/${x.id}/read`,{method:'PATCH'});reload()}}><span className="notification-dot"/><div><b>{x.title}</b><p>{x.message}</p><small>{new Date(x.created_at).toLocaleString('pt-BR')}</small></div></button>)}{!rows.length&&<Empty text="Nenhuma notificação"/>}</div></>}
export function Audit(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{load('/audit',setRows)},[]);return <><Title title="Auditoria" sub="Rastreabilidade das ações importantes"/><div className="panel table-panel"><table><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>Registro</th><th>Detalhes</th></tr></thead><tbody>{rows.map(x=><tr><td>{new Date(x.created_at).toLocaleString('pt-BR')}</td><td><span className="status">{x.action}</span></td><td>{x.entity}</td><td>{x.entity_id||'—'}</td><td>{x.details?JSON.stringify(x.details):'—'}</td></tr>)}</tbody></table></div></>}
export function Users(){const[rows,setRows]=useState<any[]>([]),[meta,setMeta]=useState<any>(),[open,setOpen]=useState(false),[message,setMessage]=useState('');const reload=()=>load('/users',setRows);useEffect(()=>{reload();load('/meta',setMeta)},[]);async function submit(e:any){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));await api('/users',{method:'POST',body:JSON.stringify({...f,is_active:true})});setOpen(false);setMessage('Usuário criado');reload()}return <><Title title="Usuários e acessos" sub="Contas, perfis e situação de acesso" action={<button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/>Novo usuário</button>}/><Notice message={message}/><div className="panel table-panel"><table><thead><tr><th>Usuário</th><th>E-mail</th><th>Perfil</th><th>Situação</th><th>Último acesso</th></tr></thead><tbody>{rows.map(x=><tr><td><b>{x.name}</b></td><td>{x.email}</td><td>{x.role}</td><td><span className="status success">{x.is_active?'Ativo':'Inativo'}</span></td><td>{x.last_login?new Date(x.last_login).toLocaleString('pt-BR'):'Nunca'}</td></tr>)}</tbody></table></div>{open&&<Modal title="Novo usuário" onClose={()=>setOpen(false)}><form className="form" onSubmit={submit}><label>Nome<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Senha inicial<input name="password" type="password" minLength={8} required/></label><label>Perfil<select name="role">{meta?.roles.map((x:string)=><option>{x}</option>)}</select></label><button className="primary">Criar usuário</button></form></Modal>}</>}
const moduleCards=[{key:'financial',label:'Financeiro',description:'Recebimentos, cobranças, inadimplência e relatórios.',integration:'Planos e contratos',icon:WalletCards},{key:'agenda',label:'Agenda',description:'Calendário, compromissos e agendamentos de serviços.',integration:'Escola e Academia',icon:CalendarDays},{key:'plans',label:'Planos e contratos',description:'Planos, assinaturas, contratos e renovações.',integration:'Financeiro, Academia e Escola',icon:FileText},{key:'academy',label:'Recursos de academia',description:'Alunos, matrículas, avaliações e modalidades.',integration:'Agenda, Planos e Financeiro',icon:Dumbbell},{key:'school',label:'Recursos de escola',description:'Alunos, responsáveis, turmas, cursos e matrículas.',integration:'Agenda, Planos e Financeiro',icon:GraduationCap}] as const;
export function Settings(){
 const[data,setData]=useState<any>(),[summary,setSummary]=useState<any>(),[message,setMessage]=useState(''),[confirm,setConfirm]=useState(false),[phrase,setPhrase]=useState('');
 const reload=()=>{load('/settings',setData);load('/admin/demo-data',setSummary)};
 useEffect(()=>{reload()},[]);
 async function save(e:any){e.preventDefault();const f=new FormData(e.currentTarget);const modules={financial:f.get('financial')==='on',agenda:f.get('agenda')==='on',plans:f.get('plans')==='on',academy:f.get('academy')==='on',school:f.get('school')==='on'};const body={...data,company_name:f.get('company_name'),segment:f.get('segment'),primary_color:f.get('primary_color'),terms:{customer:f.get('customer'),order:f.get('order'),employee:f.get('employee'),service:f.get('service')},modules};await api('/settings',{method:'PUT',body:JSON.stringify(body)});setMessage('Configurações atualizadas com sucesso.');window.dispatchEvent(new Event('modules-changed'));reload()}
 async function remove(){await api('/admin/demo-data',{method:'DELETE',body:JSON.stringify({confirmation:phrase})});setConfirm(false);setMessage('Dados demonstrativos removidos');reload()}
 if(!data)return null;
 return <><Title title="Configurações" sub="Personalize o sistema para o seu negócio"/><Notice message={message}/><form className="settings-form" onSubmit={save}>
 <article className="panel"><h3>Empresa e identidade</h3><div className="form-row"><label>Nome da empresa<input name="company_name" defaultValue={data.company_name}/></label><label>Segmento<select name="segment" defaultValue={data.segment}><option>Serviços</option><option>Academia</option><option>Escola</option><option>Clínica</option><option>Oficina</option><option>Condomínio</option></select></label></div><label>Cor principal<input name="primary_color" type="color" defaultValue={data.primary_color}/></label></article>
 <article className="panel"><h3>Nomenclaturas da interface</h3><div className="form-row"><label>Cliente<input name="customer" defaultValue={data.terms.customer}/></label><label>Ordem<input name="order" defaultValue={data.terms.order}/></label></div><div className="form-row"><label>Funcionário<input name="employee" defaultValue={data.terms.employee}/></label><label>Serviço<input name="service" defaultValue={data.terms.service}/></label></div></article>
 <article className="panel"><h3>Módulos opcionais</h3><p>Ative apenas os recursos usados pela empresa. Desativar preserva todos os dados.</p><div className="module-cards">{moduleCards.map(({key,label,description,integration,icon:Icon})=><label className="module-card" key={key}><div><b><Icon size={19}/><span>{label}</span></b><input type="checkbox" name={key} defaultChecked={!!data.modules[key]} onChange={e=>{if(e.target.checked&&(key==='academy'||key==='school')){const other=e.currentTarget.form?.elements.namedItem(key==='academy'?'school':'academy') as HTMLInputElement;if(other?.checked&&window.confirm('Academia e Escola representam segmentos diferentes. Deseja substituir o segmento atual?'))other.checked=false;else if(other?.checked)e.target.checked=false}}}/></div><span>{description}</span><small>Integra-se com: {integration}</small></label>)}</div><button className="primary">Salvar configurações</button></article></form>
 <article className="panel danger-zone"><h3>Dados demonstrativos</h3><p>Remove apenas registros identificados como demonstração. Cadastros reais permanecem intactos.</p><div className="demo-summary"><span><b>{summary?.total??'—'}</b> registros identificados</span></div><button className="danger" disabled={!summary?.has_demo_data} onClick={()=>setConfirm(true)}><Trash2 size={17}/>Excluir dados demonstrativos</button></article>
 {confirm&&<Modal title="Exclusão permanente" onClose={()=>setConfirm(false)}><p>Digite <b>EXCLUIR DADOS DEMO</b> para confirmar.</p><input value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder="EXCLUIR DADOS DEMO"/><div className="actions"><button className="ghost" onClick={()=>setConfirm(false)}>Cancelar</button><button className="danger" disabled={phrase!=='EXCLUIR DADOS DEMO'} onClick={remove}>Excluir permanentemente</button></div></Modal>}</>}
