import{useEffect,useState}from'react';import{api}from'../api';import{AlertTriangle,CalendarDays,CheckCircle2,Clock,FileText,GraduationCap,Plus,TrendingUp,Users,WalletCards}from'lucide-react';import{Empty,Loading,Title,money}from'../components/UI';import{useModules}from'../modules';
type Row={label:string;value:number};
function Metric({label,value,Icon,color='violet'}:{label:string;value:any;Icon:any;color?:string}){return <article className="metric"><span className={'icon '+color}><Icon/></span><div><small>{label}</small><strong>{value}</strong></div></article>}
function Metrics({children}:{children:React.ReactNode}){return <div className="cards">{children}</div>}
function Bars({title,rows,moneyValues=false}:{title:string;rows:Row[];moneyValues?:boolean}){const max=Math.max(...rows.map(x=>Number(x.value)),1);return <article className="panel report"><h3>{title}</h3>{rows.map(x=><div key={x.label}><span>{x.label}</span><b>{moneyValues?money(Number(x.value)):x.value}</b><i style={{width:`${Number(x.value)/max*100}%`}}/></div>)}{!rows.length&&<Empty text="Sem dados no período"/>}</article>}
function Widget({title,children}:{title:string;children:React.ReactNode}){return <article className="panel"><h3>{title}</h3>{children}</article>}
function CoreDashboard({data}:{data:any}){return <><Metrics><Metric label="Ordens abertas" value={data.orders.open} Icon={Clock}/><Metric label="Em andamento" value={data.orders.progress} Icon={TrendingUp} color="blue"/><Metric label="Concluídas" value={data.orders.done} Icon={CheckCircle2} color="green"/><Metric label="Em atraso" value={data.orders.overdue} Icon={AlertTriangle} color="red"/><Metric label="SLA atendido" value={`${data.sla_rate}%`} Icon={Clock} color="green"/><Metric label="Tempo médio" value={`${data.average_completion_hours}h`} Icon={Clock}/></Metrics><div className="dashboard-grid"><Bars title="Ordens por status" rows={data.by_status}/><Bars title="Ordens por período" rows={data.by_month}/><Bars title="Ordens por responsável" rows={data.by_employee}/><Widget title="Desempenho operacional"><div className="performance"><div className="ring" style={{'--p':`${data.completion_rate*3.6}deg`} as any}><span><b>{data.completion_rate}%</b><small>conclusão</small></span></div><div className="legend"><p><i className="dot violet"/>Total <b>{data.orders.total}</b></p><p><i className="dot green"/>Concluídas <b>{data.orders.done}</b></p><p><i className="dot red"/>Em atraso <b>{data.orders.overdue}</b></p></div></div></Widget><Widget title="Últimas ordens">{data.recent.map((x:any)=><p className="widget-row" key={x.id}><span>{x.number}<small>{x.title}</small></span><b>{x.status}</b></p>)}</Widget></div></>}
function FinancialDashboard({data}:{data:any}){return <section className="dashboard-module"><h2>Financeiro</h2><Metrics><Metric label="Receita do mês" value={money(data.month_revenue)} Icon={WalletCards} color="green"/><Metric label="Receita recebida" value={money(data.received)} Icon={WalletCards}/><Metric label="Receita pendente" value={money(data.pending)} Icon={Clock} color="red"/><Metric label="Inadimplência" value={`${data.delinquency_rate}%`} Icon={AlertTriangle} color="red"/><Metric label="Ticket médio" value={money(data.average_ticket)} Icon={TrendingUp}/><Metric label="Pagamentos vencidos" value={data.overdue} Icon={Clock} color="red"/></Metrics>{(data.overdue>0||data.pending>0)&&<div className="module-alerts">{data.overdue>0&&<span><AlertTriangle size={17}/>{data.overdue} pagamento(s) vencido(s)</span>}{data.pending>0&&<span><Clock size={17}/>{money(data.pending)} em valores pendentes</span>}</div>}<div className="dashboard-grid"><Bars title="Receita por mês" rows={data.months} moneyValues/><Bars title="Recebido x Pendente" rows={data.received_pending} moneyValues/><Bars title="Formas de pagamento" rows={data.methods} moneyValues/><Bars title="Receita por serviço" rows={data.services} moneyValues/><Widget title="Últimos pagamentos">{data.recent.map((x:any)=><p className="widget-row" key={x.key||x.id}><span>{x.method}<small>{x.status} · {x.due_date||'Sem vencimento'}</small></span><b>{money(x.amount)}</b></p>)}</Widget></div></section>}
function AgendaDashboard({data}:{data:any}){const next=data.next[0];return <section className="dashboard-module"><h2>Agenda</h2><Metrics><Metric label="Agendamentos hoje" value={data.today} Icon={CalendarDays} color="blue"/><Metric label="Próximo atendimento" value={next?new Date(next.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}):'—'} Icon={Clock}/><Metric label="Atendimentos confirmados" value={data.confirmed} Icon={CheckCircle2} color="green"/><Metric label="Cancelamentos" value={data.canceled} Icon={AlertTriangle} color="red"/></Metrics><div className="dashboard-grid"><Widget title="Agenda de hoje"><div className="day-timeline">{data.next.map((x:any)=><p className="widget-row" key={x.id}><span>{new Date(x.starts_at).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}<small>{x.title}{x.customer?` · ${x.customer}`:''}</small></span><b>{x.status}</b></p>)}{!data.next.length&&<Empty text="Nenhum atendimento hoje"/>}</div></Widget></div></section>}
function PlansDashboard({data}:{data:any}){const contracts=data.active_contracts!=null;return <section className="dashboard-module"><h2>Planos e contratos</h2><Metrics>{contracts&&<Metric label="Contratos ativos" value={data.active_contracts} Icon={FileText} color="green"/>}{contracts&&<Metric label="Contratos vencendo" value={data.expiring} Icon={Clock}/>}<Metric label="Planos ativos" value={data.active} Icon={FileText}/>{contracts&&<Metric label="Novas adesões" value={data.new_subscriptions} Icon={TrendingUp} color="green"/>}{contracts&&<Metric label="Cancelamentos" value={data.cancellations} Icon={AlertTriangle} color="red"/>}</Metrics>{contracts&&data.expiring>0&&<div className="module-alerts"><span><AlertTriangle size={17}/>{data.expiring} contrato(s) precisam de renovação nos próximos 30 dias</span></div>}{contracts&&<div className="dashboard-grid"><Widget title="Contratos vencendo">{data.expiring_contracts.map((x:any)=><p className="widget-row" key={x.id}><span>{x.customer||x.name}<small>{x.name}</small></span><b>{x.days} dias</b></p>)}{!data.expiring_contracts.length&&<Empty text="Nenhum contrato vencendo em 30 dias"/>}</Widget></div>}</section>}
function AcademyDashboard({data,plans,financial}:{data:any;plans:boolean;financial:any}){const enrollments=data.new_enrollments!=null;return <section className="dashboard-module"><h2>Academia</h2><Metrics><Metric label="Alunos ativos" value={data.active_students} Icon={GraduationCap}/>{enrollments&&<Metric label="Novas matrículas" value={data.new_enrollments} Icon={TrendingUp} color="green"/>}{enrollments&&<Metric label="Matrículas vencendo" value={data.expiring} Icon={AlertTriangle} color="red"/>}{enrollments&&<Metric label="Matrículas pausadas" value={data.paused} Icon={Clock}/>} {data.assessments!=null&&<Metric label="Avaliações agendadas" value={data.assessments} Icon={CalendarDays}/>} {plans&&enrollments&&<Metric label="Plano mais utilizado" value={data.favorite_plan} Icon={FileText}/>} {financial&&<><Metric label="Mensalidades recebidas" value={money(financial.received)} Icon={WalletCards} color="green"/><Metric label="Mensalidades pendentes" value={money(financial.pending)} Icon={WalletCards} color="red"/><Metric label="Inadimplência" value={`${financial.delinquency_rate}%`} Icon={AlertTriangle} color="red"/></>}</Metrics>{enrollments&&<div className="dashboard-grid"><Bars title="Novos alunos por mês" rows={data.by_month}/><Bars title="Alunos por modalidade" rows={data.by_modality}/>{plans&&<Bars title="Alunos por plano" rows={data.by_plan}/>}</div>}</section>}
function SchoolDashboard({data,financial}:{data:any;financial:any}){const enrollments=data.active_enrollments!=null,classes=data.active_classes!=null;return <section className="dashboard-module"><h2>Escola</h2><Metrics><Metric label="Alunos ativos" value={data.active_students} Icon={GraduationCap}/>{enrollments&&<Metric label="Matrículas ativas" value={data.active_enrollments} Icon={CheckCircle2} color="green"/>}{enrollments&&<Metric label="Novas matrículas" value={data.new_enrollments} Icon={TrendingUp} color="green"/>}{classes&&<Metric label="Turmas ativas" value={data.active_classes} Icon={Users} color="blue"/>}{classes&&<Metric label="Cursos ativos" value={data.active_courses} Icon={FileText}/>} {enrollments&&<Metric label="Matrículas pendentes" value={data.pending_enrollments} Icon={AlertTriangle} color="red"/>} {data.coordination!=null&&<Metric label="Atendimentos da coordenação" value={data.coordination} Icon={Users}/>} {financial&&<><Metric label="Mensalidades pagas" value={money(financial.received)} Icon={WalletCards} color="green"/><Metric label="Mensalidades pendentes" value={money(financial.pending)} Icon={WalletCards}/><Metric label="Mensalidades vencidas" value={financial.overdue} Icon={AlertTriangle} color="red"/></>}</Metrics>{(enrollments||classes)&&<div className="dashboard-grid">{enrollments&&<Bars title="Alunos por curso" rows={data.by_course}/>} {enrollments&&<Bars title="Alunos por turma" rows={data.by_class}/>} {enrollments&&<Bars title="Matrículas por mês" rows={data.by_month}/>} {enrollments&&<Bars title="Alunos por status" rows={data.by_status}/>} {classes&&<Widget title="Turmas">{data.classes.map((x:any)=><p className="widget-row" key={x.id}><span>{x.code}<small>{x.name}</small></span><b>{x.students}/{x.capacity}</b></p>)}{!data.classes.length&&<Empty text="Nenhuma turma ativa"/>}</Widget>}</div>}</section>}
export default function Dashboard(){
  const[data,setData]=useState<any>(),[quick,setQuick]=useState(false);
  const{modules,allowed}=useModules();
  useEffect(()=>{api('/dashboard').then(setData)},[modules]);
  if(!data)return <Loading/>;
  const quickItems:string[][]=[
    ...(allowed('orders.create')?[['Nova ordem','/ordens']]:[]),
    ...(allowed('customers.create')?[['Novo cliente','/clientes']]:[]),
    ...(allowed('services.create')?[['Novo serviço','/servicos']]:[]),
    ...(modules.agenda&&allowed('appointments.create')?[['Novo agendamento','/agenda/agendamentos']]:[]),
    ...(modules.financial&&allowed('financial.create')?[['Novo recebimento','/financeiro/recebimentos']]:[]),
    ...(modules.academy?[...(allowed('gym_enrollments.manage')?[['Novo aluno','/alunos'],['Nova matrícula','/matriculas']]:[]),...(allowed('physical_assessments.manage')?[['Nova avaliação','/avaliacoes']]:[])]:[]),
    ...(modules.school?[...(allowed('students.create')?[['Novo aluno','/alunos'],['Novo responsável','/responsaveis']]:[]),...(allowed('enrollments.manage')?[['Nova matrícula','/matriculas']]:[]),...(allowed('classes.manage')?[['Nova turma','/turmas']]:[])]:[])
  ];
  const action=quickItems.length?<div className="quick"><button className="primary" onClick={()=>setQuick(!quick)}><Plus size={17}/>Novo</button>{quick&&<div className="quick-menu">{quickItems.map(([label,path])=><a key={`${label}-${path}`} href={path}>{label}</a>)}</div>}</div>:undefined;
  return <><Title title={modules.school?'Gestão escolar':modules.academy?'Gestão da academia':'Visão geral'} sub="Acompanhe sua operação em tempo real" action={action}/><CoreDashboard data={data.core}/>{data.school&&<SchoolDashboard data={data.school} financial={data.financial}/>} {data.academy&&<AcademyDashboard data={data.academy} plans={modules.plans} financial={data.financial}/>} {data.agenda&&<AgendaDashboard data={data.agenda}/>} {data.plans&&<PlansDashboard data={data.plans}/>} {data.financial&&<FinancialDashboard data={data.financial}/>}</>
}
