import{useEffect,useMemo,useState}from'react';
import type{ReactNode}from'react';
import{LayoutDashboard,ClipboardList,Users,BriefcaseBusiness,Wrench,CalendarDays,WalletCards,ChartNoAxesCombined,Bell,ShieldCheck,UserCog,Settings as Gear,LogOut,Search,Menu,GraduationCap,Dumbbell,FileText,BookOpen,UserRoundCheck,RefreshCw,CreditCard}from'lucide-react';
import{api,token}from'./api';import type{Page,User}from'./types';import Login from'./pages/Login';import Dashboard from'./pages/Dashboard';import{Customers,Directory,Orders}from'./pages/Operations';import Agenda from'./pages/AgendaPage';import Finance from'./pages/FinancePage';import Plans from'./pages/PlansPage';import Reports from'./pages/ReportsPage';import Students from'./pages/StudentsPage';import Departments from'./pages/DepartmentsPage';import{Audit,Notifications,Settings}from'./pages/Admin';import UserPage from'./pages/UsersPage';import{ModuleProvider,useModules}from'./modules';import type{ModuleKey}from'./modules';import{ResourcePage}from'./pages/ModulePages';import {JobPositionsPage, ProfilesPage, PermissionsPage} from './pages/AccessPages';

type NavItem={id:Page;label:string;icon:any;module?:ModuleKey;permission?:string;adminOnly?:boolean;path:string};type Group={label:string;items:NavItem[]};
const routes:Record<string,Page>={'/':'dashboard','/dashboard':'dashboard','/ordens':'orders','/clientes':'customers','/funcionarios':'employees','/servicos':'services','/setores':'departments','/agenda':'agenda','/agenda/agendamentos':'agenda_appointments','/agenda/minha-agenda':'my_agenda','/financeiro':'finance','/financeiro/recebimentos':'finance_receipts','/financeiro/contas-receber':'receivables','/financeiro/pagamentos':'payments','/financeiro/relatorios':'financial_reports','/planos':'plans','/contratos':'contracts','/assinaturas':'subscriptions','/renovacoes':'renewals','/alunos':'students','/matriculas':'enrollments','/avaliacoes':'assessments','/professores':'teachers','/modalidades':'modalities','/responsaveis':'guardians','/turmas':'classes','/cursos':'courses','/coordenacao':'coordination','/documentos':'documents','/relatorios':'reports','/notificacoes':'notifications','/auditoria':'audit','/usuarios':'users','/configuracoes':'settings','/configuracoes/cargos':'job_positions','/configuracoes/perfis':'profiles','/configuracoes/permissoes':'permissions'};
const pathFor=(page:Page)=>Object.entries(routes).find(([,value])=>value===page)?.[0]||'/dashboard';
const searchPage=(type:string):Page=>({order:'orders',customer:'customers',student:'students',employee:'employees',teacher:'teachers',service:'services',plan:'plans',payment:'finance',charges:'finance',contracts:'contracts',subscriptions:'subscriptions',renewals:'renewals',enrollments:'enrollments',guardians:'guardians',classes:'classes',courses:'courses',assessments:'assessments',modalities:'modalities',coordination:'coordination',documents:'documents'}[type] as Page)||'dashboard';
const routeAccess:Partial<Record<Page,[ModuleKey,string]>>={agenda:['agenda','appointments.view'],agenda_appointments:['agenda','appointments.view'],my_agenda:['agenda','appointments.view'],finance:['financial','financial.view'],finance_receipts:['financial','financial.view'],receivables:['financial','financial.view'],payments:['financial','financial.view'],financial_reports:['financial','financial.view'],plans:['plans','plans.view'],contracts:['plans','contracts.view'],subscriptions:['plans','contracts.view'],renewals:['plans','contracts.view'],assessments:['academy','physical_assessments.manage'],modalities:['academy','gym_students.view'],guardians:['school','students.view'],classes:['school','classes.view'],courses:['school','classes.view'],coordination:['school','classes.manage'],documents:['school','students.view']};
function Shell(){
 const initial=routes[location.pathname]||'dashboard',[page,setPage]=useState<Page>(initial),[mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<any[]>([]);const{modules,ready,enabled,allowed,context,revision}=useModules();const user=context?.user||JSON.parse(localStorage.getItem('user')||'{}'),isAdmin=!!context?.is_admin;const special=modules.school||modules.academy,segment=modules.school?'Escola':modules.academy?'Academia':'Gestão de serviços',studentLabel=special?'Alunos':'Clientes';
 const groups=useMemo<Group[]>(()=>[
  {label:'',items:[{id:'dashboard',label:'Visão geral',icon:LayoutDashboard,permission:'dashboard.view',path:'/dashboard'}]},
  ...(modules.school?[{label:'ESCOLA',items:[{id:'students',label:'Alunos',icon:GraduationCap,module:'school',permission:'students.view',path:'/alunos'},{id:'guardians',label:'Responsáveis',icon:Users,module:'school',permission:'students.view',path:'/responsaveis'},{id:'enrollments',label:'Matrículas',icon:FileText,module:'school',permission:'enrollments.manage',path:'/matriculas'},{id:'classes',label:'Turmas',icon:BookOpen,module:'school',permission:'classes.view',path:'/turmas'},{id:'courses',label:'Cursos',icon:BookOpen,module:'school',permission:'classes.view',path:'/cursos'},{id:'teachers',label:'Professores',icon:UserRoundCheck,module:'school',permission:'classes.view',path:'/professores'},{id:'coordination',label:'Coordenação',icon:BriefcaseBusiness,module:'school',permission:'classes.manage',path:'/coordenacao'},{id:'documents',label:'Documentos',icon:FileText,module:'school',permission:'students.view',path:'/documentos'}] as NavItem[]}]:[]),
  ...(modules.academy?[{label:'ACADEMIA',items:[{id:'students',label:'Alunos',icon:Dumbbell,module:'academy',permission:'gym_students.view',path:'/alunos'},{id:'enrollments',label:'Matrículas',icon:FileText,module:'academy',permission:'gym_enrollments.manage',path:'/matriculas'},...(modules.plans?[{id:'plans',label:'Planos',icon:FileText,module:'plans',permission:'plans.view',path:'/planos'} as NavItem]:[]),{id:'assessments',label:'Avaliações físicas',icon:ChartNoAxesCombined,module:'academy',permission:'physical_assessments.manage',path:'/avaliacoes'},{id:'teachers',label:'Professores',icon:UserRoundCheck,module:'academy',permission:'gym_students.view',path:'/professores'},{id:'modalities',label:'Modalidades',icon:Dumbbell,module:'academy',permission:'gym_students.view',path:'/modalidades'}] as NavItem[]}]:[]),
  {label:'OPERAÇÃO',items:[{id:'orders',label:special?'Atendimentos':'Ordens',icon:ClipboardList,permission:'orders.view',path:'/ordens'},{id:'customers',label:studentLabel,icon:Users,permission:'customers.view',path:'/clientes'},{id:'employees',label:special?'Equipe':'Funcionários',icon:BriefcaseBusiness,permission:allowed('employees.view')?'employees.view':'employees.view_department',path:'/funcionarios'},{id:'services',label:'Serviços',icon:Wrench,permission:'services.view',path:'/servicos'},{id:'departments',label:'Setores',icon:BriefcaseBusiness,permission:'departments.manage',path:'/setores'}]},
  {label:'AGENDA',items:[{id:'agenda',label:'Calendário',icon:CalendarDays,module:'agenda',permission:'appointments.view',path:'/agenda'},{id:'agenda_appointments',label:'Agendamentos',icon:CalendarDays,module:'agenda',permission:'appointments.view',path:'/agenda/agendamentos'},{id:'my_agenda',label:'Minha agenda',icon:UserRoundCheck,module:'agenda',permission:'appointments.view',path:'/agenda/minha-agenda'}]},
  {label:'FINANCEIRO',items:[{id:'finance',label:'Visão geral',icon:WalletCards,module:'financial',permission:'financial.view',path:'/financeiro'},{id:'finance_receipts',label:'Recebimentos',icon:CreditCard,module:'financial',permission:'financial.view',path:'/financeiro/recebimentos'},{id:'receivables',label:'Contas a receber',icon:CreditCard,module:'financial',permission:'financial.view',path:'/financeiro/contas-receber'},{id:'payments',label:'Pagamentos',icon:WalletCards,module:'financial',permission:'financial.view',path:'/financeiro/pagamentos'},{id:'financial_reports',label:'Relatórios financeiros',icon:ChartNoAxesCombined,module:'financial',permission:'financial.view',path:'/financeiro/relatorios'}]},
  {label:'PLANOS E CONTRATOS',items:[{id:'plans',label:'Planos',icon:FileText,module:'plans',permission:'plans.view',path:'/planos'},{id:'contracts',label:'Contratos',icon:FileText,module:'plans',permission:'contracts.view',path:'/contratos'},{id:'subscriptions',label:'Assinaturas',icon:CreditCard,module:'plans',permission:'contracts.view',path:'/assinaturas'},{id:'renewals',label:'Renovações',icon:RefreshCw,module:'plans',permission:'contracts.view',path:'/renovacoes'}]},
  {label:'GESTÃO',items:[{id:'reports',label:'Relatórios',icon:ChartNoAxesCombined,permission:allowed('reports.view')?'reports.view':'reports.view_department',path:'/relatorios'},{id:'notifications',label:'Notificações',icon:Bell,path:'/notificacoes'}]},
  {label:'ADMINISTRAÇÃO',items:[{id:'users',label:'Usuários',icon:UserCog,adminOnly:true,permission:'users.manage',path:'/usuarios'},{id:'audit',label:'Auditoria',icon:ShieldCheck,adminOnly:true,permission:'audit.view',path:'/auditoria'},{id:'settings',label:'Configurações',icon:Gear,adminOnly:true,permission:'settings.manage',path:'/configuracoes'},{id:'job_positions',label:'Cargos',icon:BriefcaseBusiness,adminOnly:true,permission:'roles.manage',path:'/configuracoes/cargos'},{id:'profiles',label:'Perfis de acesso',icon:ShieldCheck,adminOnly:true,permission:'profiles.manage',path:'/configuracoes/perfis'},{id:'permissions',label:'Permissões',icon:UserCog,adminOnly:true,permission:'permissions.manage',path:'/configuracoes/permissoes'}]}
 ],[modules,special,studentLabel,allowed]);
 const visibleGroups=groups.map(group=>({...group,items:group.items.filter(x=>(!x.adminOnly||isAdmin)&&(!x.module||enabled(x.module))&&(!x.permission||allowed(x.permission)))})).filter(x=>x.items.length);const access=routeAccess[page],segmentPermissions:Partial<Record<Page,string>>=modules.school?{students:'students.view',enrollments:'enrollments.manage',teachers:'classes.view'}:modules.academy?{students:'gym_students.view',enrollments:'gym_enrollments.manage',teachers:'gym_students.view'}:{},segmentRouteAllowed=!['students','enrollments','teachers'].includes(page)||!!segmentPermissions[page]&&allowed(segmentPermissions[page]!),adminRestricted=['users','audit','settings','job_positions','profiles','permissions'].includes(page)&&!isAdmin,corePermissions:Partial<Record<Page,string[]>>={dashboard:['dashboard.view'],orders:['orders.view'],customers:['customers.view'],employees:['employees.view','employees.view_department'],services:['services.view'],departments:['departments.manage'],reports:['reports.view','reports.view_department'],users:['users.manage'],audit:['audit.view'],settings:['settings.manage'],job_positions:['roles.manage'],profiles:['profiles.manage'],permissions:['permissions.manage']},authorized=!adminRestricted&&(!corePermissions[page]||corePermissions[page]!.some(allowed))&&segmentRouteAllowed&&(!access||(enabled(access[0])&&allowed(access[1])));
 function navigate(next:Page){setPage(next);history.pushState({},'',pathFor(next));setMobile(false)}
 useEffect(()=>{const pop=()=>setPage(routes[location.pathname]||'dashboard');addEventListener('popstate',pop);return()=>removeEventListener('popstate',pop)},[]);useEffect(()=>{document.body.dataset.page=page},[page]);useEffect(()=>{const timer=setTimeout(()=>query.length>1?api<any[]>(`/search?q=${encodeURIComponent(query)}`).then(setResults).catch(()=>setResults([])):setResults([]),250);return()=>clearTimeout(timer)},[query]);
 const resource=(module:ModuleKey,resource:string,title:string)=><ResourcePage module={module} resource={resource} description={`${title} de ${segment.toLowerCase()}`}/>;const pages:Record<Page,ReactNode>={dashboard:<Dashboard/>,orders:<Orders/>,customers:<Customers/>,employees:<Directory kind="employees"/>,services:<Directory kind="services"/>,departments:<Departments/>,agenda:<Agenda/>,agenda_appointments:<Agenda/>,my_agenda:<Agenda/>,finance:<Finance/>,finance_receipts:<Finance/>,receivables:<Finance/>,payments:<Finance/>,financial_reports:<Reports/>,plans:<Plans/>,contracts:resource('plans','contracts','Contratos'),subscriptions:resource('plans','subscriptions','Assinaturas'),renewals:resource('plans','renewals','Renovações'),students:<Students/>,enrollments:modules.school?resource('school','enrollments','Matrículas'):resource('academy','enrollments','Matrículas'),assessments:resource('academy','assessments','Avaliações'),teachers:<Directory kind="employees"/>,modalities:resource('academy','modalities','Modalidades'),guardians:resource('school','guardians','Responsáveis'),classes:resource('school','classes','Turmas'),courses:resource('school','courses','Cursos'),coordination:resource('school','coordination','Coordenação'),documents:resource('school','documents','Documentos'),reports:<Reports/>,notifications:<Notifications/>,audit:<Audit/>,users:<UserPage/>,settings:<Settings/>,job_positions:<JobPositionsPage/>,profiles:<ProfilesPage/>,permissions:<PermissionsPage/>};
 if(!ready)return null;return <div className="app"><aside className={mobile?'open':''}><div className="logo"><b>N</b><span>NovaFlow<small>{segment.toUpperCase()}</small></span></div><nav>{visibleGroups.map(group=><section className="nav-group" key={group.label}>{group.label&&<small>{group.label}</small>}{group.items.map(({id,label,icon:Icon})=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}><Icon size={18}/>{label}</button>)}</section>)}</nav><div className="profile"><div className="avatar">{user.name?.[0]}</div><span>{user.name}<small>{context?.profile?.name||context?.profile_name}</small></span><button title="Sair" onClick={()=>{localStorage.clear();location.reload()}}><LogOut size={17}/></button></div></aside><section className="content"><header><button className="hamb" onClick={()=>setMobile(!mobile)}><Menu/></button><div className="global-search"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar ordens, ${studentLabel.toLowerCase()}…`}/></div>{results.length>0&&<div className="search-results">{results.map(x=><button key={`${x.type}-${x.id}`} onClick={()=>{navigate(searchPage(x.type));setQuery('');setResults([])}}><b>{x.title}</b><small>{x.subtitle}</small></button>)}</div>}</div><span className="live"><i/> Sistema operacional</span></header><main className="page">{authorized?<div key={revision}>{pages[page]}</div>:<article className="panel module-blocked"><ShieldCheck/><h2>{adminRestricted?'Acesso exclusivo de administrador.':'Acesso não permitido'}</h2><p>{adminRestricted?'Somente administradores podem acessar e alterar as configurações do sistema.':'Seu perfil não permite acessar esta página ou o módulo está desativado. Solicite a revisão ao administrador.'}</p><button className="primary" onClick={()=>navigate('dashboard')}>Voltar ao dashboard</button></article>}</main></section></div>
}
export default function App(){const[auth,setAuth]=useState(!!token());return auth?<ModuleProvider><Shell/></ModuleProvider>:<Login done={()=>setAuth(true)}/>}
